# Generated by Django 3.1.5 on 2021-01-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descrioption',
            new_name='description',
        ),
    ]
