# Generated by Django 3.1.5 on 2021-02-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210210_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FilePathField(path='static\\img\\'),
        ),
    ]
