# Generated by Django 3.1.5 on 2021-02-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20210210_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FilePathField(path='projects\\static\\projects'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='projects\\static\\projects'),
        ),
    ]
