# Generated by Django 3.1.5 on 2021-02-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210214_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FilePathField(path='projects/static/projects'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='projects/static/projects'),
        ),
    ]
