# Generated by Django 3.1.5 on 2021-02-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20210214_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
