# Generated by Django 3.1.5 on 2021-02-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_image_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images'),
        ),
    ]
