# Generated by Django 3.1.5 on 2021-02-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20210215_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='projects/static/projects/images'),
        ),
    ]
