# Generated by Django 3.1.5 on 2021-02-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20210216_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
