# Generated by Django 3.1.5 on 2021-02-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_project_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='website',
            new_name='repoGitLink',
        ),
        migrations.AddField(
            model_name='project',
            name='runningProgramLink',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
