# Generated by Django 3.1.5 on 2021-02-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20210216_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images'),
        ),
    ]
