# Generated by Django 3.1.5 on 2021-02-14 17:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('profilePicture', models.FilePathField(path='home/')),
            ],
        ),
    ]
