# Generated by Django 3.1.5 on 2021-02-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='profilePicture',
            field=models.FilePathField(path='home/static/home/'),
        ),
    ]
