# Generated by Django 3.1.5 on 2021-02-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210214_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='profilePicture',
            field=models.FilePathField(path='home/static/home'),
        ),
    ]
