# Generated by Django 3.1.5 on 2021-02-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210215_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='profilePicture',
            field=models.FilePathField(path='home/static/home/'),
        ),
    ]
