# Generated by Django 3.1.5 on 2021-02-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210215_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='profilePicture',
            field=models.FilePathField(path='images'),
        ),
    ]
