# Generated by Django 3.1.5 on 2021-02-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210216_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to='home/images'),
        ),
    ]
